### PR TITLE
Update codeToRun.R

### PR DESCRIPTION
**Pull request by fdefalco**
add pathToDriver to connectionDetails

### CODE REVIEW

**Comment by schuemie** [comment]
I'm not sure just adding a mysterious path for people to set will help. Especially since the recommended practice is to set the path to the jars in an environmental variable. 

We have the [DatabaseConnector vignette](https://ohdsi.github.io/DatabaseConnector/articles/UsingDatabaseConnector.html) we could point to for people that haven't yet figured out how to use DatabaseConnector to connect to their database. Or maybe we could create a separate vignette or page on the HADES website?

**Comment by fdefalco** [comment]
Yes, your suggestions sound better.  As it stands, it just throws an error when you try to run it as is, my fix only prevents that.

**Comment by schuemie** [comment]
I've split the DatabaseConnector vignette, so we have a separate one just on getting to the point where people can connect, which is what people will need to run network studies. The new vignette is currently available as [PDF](https://github.com/OHDSI/DatabaseConnector/raw/develop/inst/doc/Connecting.pdf) only, but will be an HTML webpage once I've released a new version of DatabaseConnector (which hopefully will be soon). 

I recommend we point people to this in our network studies.

**Comment by schuemie** [comment]
(I've also improved the error messages when the pathToDriver isn't specified)

**Comment by schuemie** [comment]
The instructions for how to connect to a database are now available as [a website](http://ohdsi.github.io/DatabaseConnector/articles/Connecting.html). I recommend linking to that in the instructions.

**Comment by ericaVoss** [comment]
Based on what is discussed above, I will perform this in another pull request.  

Here is what I added:
https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/commit/81d1fecce8b17814a895c487235c9503a99bc284

**Pull request closed without merging**
